<Project>
  <PropertyGroup>
    <CharacterSet>Unicode</CharacterSet>
  </PropertyGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <ClCompile>
      <RuntimeLibrary>MultiThreaded</RuntimeLibrary>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <ClCompile>
      <RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>
      <SDLCheck>true</SDLCheck>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <SuppressStartupBanner>false</SuppressStartupBanner>
      <LanguageStandard>stdcpplatest</LanguageStandard>
      <WarningLevel>Level3</WarningLevel>
      <ConformanceMode>true</ConformanceMode>
      <EnforceTypeConversionRules>true</EnforceTypeConversionRules>
      <RuntimeTypeInfo>true</RuntimeTypeInfo>
      <TreatWarningAsError>true</TreatWarningAsError>
      <BrowseInformation>true</BrowseInformation>
      <DiagnosticsFormat>Caret</DiagnosticsFormat>
    </ClCompile>
    <Link>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <AssemblyDebug>true</AssemblyDebug>
      <SubSystem>Console</SubSystem>
    </Link>
    <Manifest>
      <EnableDpiAwareness>PerMonitorHighDPIAwareV2</EnableDpiAwareness>
    </Manifest>
  </ItemDefinitionGroup>
</Project>
